export const CHECK_USER_EXISTS_BY_EMAIL = 'CHECK_USER_BY_EMAIL'
export const USER_EXISTS_BY_EMAIL = 'USER_EXISTS_BY_EMAIL'
export const USER_DNE_BY_EMAIL = 'USER_DNE_BY_EMAIL'

export const CHECK_EMAIL_EXISTS = 'CHECK_EMAIL_EXISTS'
export const EMAIL_EXISTS = 'EMAIL_EXISTS'
export const EMAIL_DNE = 'EMAIL_DNE'

export const SEND_VERIFICATION_CODE = 'SEND_VERIFICATION_CODE'
export const VERIFICATION_CODE_SENT = 'VERIFICATION_CODE_SENT'
export const VERIFICATION_CODE_NOT_SENT = 'VERIFICATION_CODE_NOT_SENT'
export const EMAIL_VERIFIED = 'EMAIL_VERIFIED'
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED'

export const CHECK_USER_EXISTS_BY_USERNAME = 'CHECK_USER_EXISTS_BY_USERNAME'
export const USER_EXISTS_BY_USERNAME = 'USER_EXISTS_BY_USERNAME'
export const USER_DNE_BY_USERNAME = 'USER_DNE_BY_USERNAME'
