export const PROVIDE_EMAIL = 'PROVIDE_EMAIL'
export const USER_EXISTS_BY_EMAIL = 'USER_EXISTS_BY_EMAIL'

export const VERIFICATION_CODE_SEND_ERROR = 'VERIFICATION_CODE_SEND_ERROR'
export const PROVIDE_VERIFICATION_CODE = 'PROVIDE_VERIFICATION_CODE'

export const PROVIDE_USERNAME = 'PROVIDE_USERNAME'
export const USER_EXISTS_BY_USERNAME = 'USER_EXISTS_BY_USERNAME'
